# Site settings
title:          365stories
description:    "365 days. 365 stories."
url:            "https://365stories.io"



# Author
author:
  name:         Finn Buzzed
  url:          https://chocciibuster.github.io
  email:        jambuzzed@gmail.com

#about - profile picture
profilepicture: /assets/images/pic.jpg

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale
